apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fargate-flux-test
  region: us-east-2
  version: "1.21"
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      attachPolicyARNs: 
        - arn:aws:iam::365268860483:policy/AmazonEKS_EFS_CSI_Driver_Policy
fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: flux-system
gitops:
  flux:
    gitProvider: github
    flags:
      owner: "walkermiller"
      repository: "eks-sample-deploy"
      private: "false"
      branch: main
      namespace: flux-system
      path: clusters/test-cluster