apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fargate-flux-test
  region: us-east-2
  version: 1.21
iam:
  withOIDC: true
fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: flux-system
gitops:
  flux:
    gitProvider: github
    flags:
      owner: "Walker"
      repository: 
      private: false
      branch: main
      namespace: flux-system
      path: clusters/test-cluster